[0m10:39:43.197253 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdc2eef1850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdc2ebd13d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdc2eef3380>]}


============================== 10:39:43.205924 | 673670a6-209a-46fe-9d32-e4df49c2ce05 ==============================
[0m10:39:43.205924 [info ] [MainThread]: Running with dbt=1.9.4
[0m10:39:43.207144 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/airflow/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m10:39:43.260214 [info ] [MainThread]: dbt version: 1.9.4
[0m10:39:43.261549 [info ] [MainThread]: python version: 3.12.10
[0m10:39:43.262910 [info ] [MainThread]: python path: /home/airflow/.local/bin/python
[0m10:39:43.286016 [info ] [MainThread]: os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[0m10:39:43.292159 [info ] [MainThread]: Using profiles dir at /home/airflow/.dbt
[0m10:39:43.293808 [info ] [MainThread]: Using profiles.yml file at /home/airflow/.dbt/profiles.yml
[0m10:39:43.296386 [info ] [MainThread]: Using dbt_project.yml file at /opt/airflow/dbt_project.yml
[0m10:39:43.299654 [info ] [MainThread]: Configuration:
[0m10:39:43.302063 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m10:39:43.304330 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m10:39:43.306199 [info ] [MainThread]: Required dependencies:
[0m10:39:43.309455 [debug] [MainThread]: Executing "git --help"
[0m10:39:43.312715 [info ] [MainThread]:  - git [[31mERROR[0m]

[0m10:39:43.313534 [info ] [MainThread]: Connection test skipped since no profile was found
[0m10:39:43.315711 [info ] [MainThread]: [31m3 checks failed:[0m
[0m10:39:43.319601 [info ] [MainThread]: dbt looked for a profiles.yml file in /home/airflow/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m10:39:43.320975 [info ] [MainThread]: Project loading failed for the following reason:
 project path </opt/airflow/dbt_project.yml> not found

[0m10:39:43.324805 [info ] [MainThread]: Error from git --help: User does not have permissions for this command: "git"

[0m10:39:43.327073 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.21714637, "process_in_blocks": "16", "process_kernel_time": 0.160615, "process_mem_max_rss": "103184", "process_out_blocks": "456", "process_user_time": 2.429304}
[0m10:39:43.328492 [debug] [MainThread]: Command `dbt debug` failed at 10:39:43.328305 after 0.22 seconds
[0m10:39:43.331410 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdc2ea52ea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdc32c331d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdc2ea378c0>]}
[0m10:39:43.332453 [debug] [MainThread]: Flushing usage events
[0m10:39:44.975510 [debug] [MainThread]: An error was encountered while trying to flush usage events
